//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboUSER.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class LABOEntities : DbContext
    {
        public LABOEntities()
            : base("name=LABOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CityMaster> CityMasters { get; set; }
        public DbSet<CountryMaster> CountryMasters { get; set; }
        public DbSet<StateMaster> StateMasters { get; set; }
        public DbSet<tbl_ContactUs> tbl_ContactUs { get; set; }
        public DbSet<tbl_CountryMaster> tbl_CountryMaster { get; set; }
        public DbSet<tbl_JobMessage> tbl_JobMessage { get; set; }
        public DbSet<tbl_Jobs> tbl_Jobs { get; set; }
        public DbSet<tbl_PagePermission> tbl_PagePermission { get; set; }
        public DbSet<tbl_Roles> tbl_Roles { get; set; }
        public DbSet<tbl_Setting> tbl_Setting { get; set; }
        public DbSet<tbl_StateMaster> tbl_StateMaster { get; set; }
        public DbSet<tbl_Users> tbl_Users { get; set; }
        public DbSet<view_user_job> view_user_job { get; set; }
        public DbSet<tbl_JobEmployees> tbl_JobEmployees { get; set; }
        public DbSet<tbl_JobPayment> tbl_JobPayment { get; set; }
    
        public virtual ObjectResult<GET_JOB_EMPLOYEE_Result> GET_JOB_EMPLOYEE(Nullable<int> jobid, Nullable<System.Guid> userid)
        {
            var jobidParameter = jobid.HasValue ?
                new ObjectParameter("jobid", jobid) :
                new ObjectParameter("jobid", typeof(int));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_JOB_EMPLOYEE_Result>("GET_JOB_EMPLOYEE", jobidParameter, useridParameter);
        }
    
        public virtual ObjectResult<dashboard_count_Result> dashboard_count(string type, Nullable<System.Guid> userid)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dashboard_count_Result>("dashboard_count", typeParameter, useridParameter);
        }
    }
}
