//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboUSER.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tbl_Jobs
    {
        public long Pk_JobId { get; set; }
        public string UniqueJobId { get; set; }
        public Nullable<System.Guid> ClientUserId { get; set; }
        [Required(ErrorMessage = "Title is required.")]
        public string JobTitle { get; set; }
        [Required(ErrorMessage = "Description is required.")]

        public string JobDescription { get; set; }
        [Required(ErrorMessage = "Location is required.")]
        public string JobLocation { get; set; }
        [Required(ErrorMessage = "Timing is required.")]
        public string JobTiming { get; set; }
        [Required(ErrorMessage = "Category is required.")]
        public string JobCategory { get; set; }
        [Required(ErrorMessage = "No.of employee is required.")]
        [RegularExpression(@"[0-9]*", ErrorMessage = "No Of Employee must be a Numbers only.")]
        public Nullable<int> NoOfEmployeeNeeded { get; set; }
        [Required(ErrorMessage = "Amount is required.")]
        [RegularExpression(@"[0-9]*", ErrorMessage = "Amount must be a Numbers only.")]
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> CompanyFee { get; set; }
        public string ClientFeePaymentStatus { get; set; }
        public Nullable<System.DateTime> ClientFeePaymentDate { get; set; }
        public string Note { get; set; }
        public string JobStatus { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
