//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboUSER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StateMaster
    {
        public long Pk_StateId { get; set; }
        public string StateName { get; set; }
        public Nullable<long> Fk_CountryId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
