//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboUSER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Setting
    {
        public long Pk_SettingId { get; set; }
        public string AdminEmailId { get; set; }
        public string SenderEmailId { get; set; }
        public string Host { get; set; }
        public string Port { get; set; }
        public Nullable<bool> IsSSL { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string SiteLogo { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<bool> IsTaxFree { get; set; }
        public Nullable<decimal> CompanyFee { get; set; }
        public string FacebookLink { get; set; }
        public string TwitterLink { get; set; }
        public string InstagramLink { get; set; }
    }
}
