//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboUSER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_JobPayment
    {
        public long Pk_JobPaymentId { get; set; }
        public Nullable<long> Fk_JobId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string TransactionId { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
