//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboUSER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_JobEmployees
    {
        public long Pk_JobEmployeeId { get; set; }
        public Nullable<long> Fk_JobId { get; set; }
        public Nullable<System.Guid> fromUserId { get; set; }
        public string EmplyeeFeePaymentStatus { get; set; }
        public string EmplyeeFeePaymentDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> toUserId { get; set; }
        public string fromUserName { get; set; }
    }
}
