//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboUSER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PagePermission
    {
        public System.Guid Pk_PageId { get; set; }
        public string PageName { get; set; }
        public Nullable<bool> IsClient { get; set; }
        public Nullable<bool> IsEmployee { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
