//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboUSER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_user_job
    {
        public System.Guid Pk_UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string MidleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string EmailId { get; set; }
        public string ContactNo { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string UserImage { get; set; }
        public Nullable<System.Guid> Fk_RoleId { get; set; }
        public string Gov_IssueId { get; set; }
        public string EligibleWorkId { get; set; }
        public string PoliceVerification { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public Nullable<long> Fk_CountryId { get; set; }
        public Nullable<long> Fk_StateId { get; set; }
        public Nullable<long> Fk_CityId { get; set; }
        public string ZipCode { get; set; }
        public string UserType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsBlocked { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> Fk_JobId { get; set; }
        public string EmplyeeFeePaymentStatus { get; set; }
    }
}
